services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}
    ports:
      - "3000:3000"
    # НЕТ volumes — не перезатираем .next
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    command: npm run start