services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DATABASE_URL
        - NEXTAUTH_URL
        - AUTH_SECRET
    ports:
      - "3000:3000"
    # НЕТ volumes — не перезатираем .next
    environment:
      - NODE_ENV=production
    env_file:
      - .env
      - .env.local
    сommand: npm run start
